version: "3.8"

services:
  api:
    build:
      context: ./api
    tty: true
    env_file: .env
    ports:
      - ${API_PORT}:8080
    volumes:
      - ./api:/src
    depends_on:
      - db
    container_name: golang_todos_api

  db:
    build:
      context: ./db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file: .env
    ports:
      - ${DB_PORT}:3306
    volumes:
      - dbdata:/var/lib/mysql
      - ./db/sql:/docker-entrypoint-initdb.d
    container_name: golang_todos_db

volumes:
  dbdata:
